# Site settings
title: Daniel Lakin
email: dlakin01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer, Actor, and Dog Lover
baseurl:  # the subpath of your site, e.g. /blog/
url:  dlakin01.github.io/folio
twitter_username: twitter_username
github_username:  DLakin01

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

plugins: [jekyll-paginate]


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
